### ISSUE TITLE
report editor popups upon mouseover has gone away?

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1777] opened 2021-03-06 15:20 UTC
Not sure if this was intentional, but in the latest version of the report editor, when you mouse over the various icons at the top of the editor there aren't any popups anymore.  [Win10, Firefox86].

Also wondering if we fixed whatever were the recent issues causing various students' reports to crash or get erased or whatever the various problems were.

**Comment by Planeshifter** [comment] 2021-03-06 18:11
The issue causing reports not getting saved should be fixed, but will test some more.

I cannot reproduce tooltips not showing up in the report editor  of the data explorer on Firefox 86. Also didn't make any changes to the them. Would you be able to please point me to a lesson with that problem? The tooltips are disabled for touch devices due to usability problems otherwise, a decision which we might want to revise at some point. I am wondering whether for some reason your device gets confused as a touch device?

**Comment by gweinberg** [comment] 2021-03-06 18:33
see here:
https://cmu.zoom.us/rec/play/3m-elsKj-eqOi-ab7wATs7pdfjUc4rMIQ5iCo0NV_nrem5fb-VLX-wEhzcew3a2m3foHCY2b_NlZN_M0.VpZHOmn52v5sqqm5?continueMode=true

**Comment by Planeshifter** [comment] 2021-03-10 00:37
Fixed per c38c3927a93da5c86aac898fcab0b9e1f618c031.

**Closed by Planeshifter** 2021-03-10 00:37 UTC

**Comment by gweinberg** [comment] 2021-03-17 16:32
Did this change deactive the mouseover on the probability plots?  I'm not getting any popup probabilities anymore when mousing over the bars on the binomial probability plot, was that intentional?  (e.g., https://isle.stat.cmu.edu/36-200-F_36-247-spring21/lab6/)

**Comment by Planeshifter** [comment] 2021-03-17 19:36
If I am not mistaken, we never had tooltips in the distribution widgets.  See e.g. here for a version of the widget that was uploaded a while ago: 

https://isle.stat.cmu.edu/widgets/binomial-distribution/

However, that certainly would be a useful feature an should be fairly easy to add. Will look into it.

**Comment by gweinberg** [comment] 2021-03-17 19:39
Maybe I'm misremembering.  I thought the bars were mousable, and they popped up the probabilities.  [Would be useful]
