### ISSUE TITLE
Field for private instructor information

### ISSUE THREAD

**Issue by sacole167** [isle-project/isle-editor#1288] opened 2020-09-02 22:01 UTC
It would be nice to have private field where you can enter notes that can only be seen by instructors. For example, in a FreeTextQuestion, this might contain the points that the instructors hopes to elicit in the responses.

**Comment by Planeshifter** [comment] 2020-09-03 00:10
Thanks for this suggestion! We have been floating around some ideas around instructor notes attached to the lessons themselves (aside from the editor in the instructor panel) as well. Will post to this thread once we have something to share.

**Comment by gweinberg** [comment] 2020-09-23 23:15
To piggyback on this, for the purpose of instructors screen sharing in class and not wanting to reveal what might be private notes (or accidentally revealing identifiable info inside the instructor panel), instructors could have a "protected view" button which would disable certain instructor functionalities (like, for instance, on-screen instructor notes).  The problem is that this couldn't simply be a "student view" because instructors would still want to share plots or word clouds of aggregate student answers.

Maybe there should be a functionality where, for any given lesson, instructors could specify ahead of time what things would be shown/hidden in "protected view" (a series of checkboxes inside the instructor panel?).

Thinking even further, in certain contexts I'd like (as the professor) the power to specify ahead of time for my TAs what they could and could not show in "protected mode" (that way I could guarantee that no TA would accidentally reveal something they shouldn't).  There should be different levels of ISLE user:

"owner/teacher", who would have ability to upload/download lessons, delete lessons*, add/delete other users, view course data, and manipulate other users' permissions (including what their "protected mode" would show and then lock out the ability of those users to change that setting;

"assistant/TA", who would have access to the instructor panel in each lesson, but not access to course data, not the ability to show/hide/delete lessons, not the ability to decide other users' "protected mode" would show;

"student", who would have current student access.

[I guess these should be separate requests?]


( * by the way, does "delete lesson" give a warning before deleting?  I've always been too afraid to test it out in case it doesn't)

**Comment by Planeshifter** [comment] 2020-09-23 23:58
> [I guess these should be separate requests?]

Yes, please.

> ( * by the way, does "delete lesson" give a warning before deleting? I've always been too afraid to test it out in case it doesn't)

Yes, there is a modal window that pops up and asks one to confirm.

**Comment by Planeshifter** [comment] 2021-02-08 18:42
Closing this for now, as the original request should be sufficiently addressed by the updated sticky notes functionality. With latest changes, sticky notes will now also be hidden when in the presentation view of a lesson.

**Closed by Planeshifter** 2021-02-08 18:42 UTC
Labels: enhancement
