### ISSUE TITLE
numbers of ordered list render in pdf as all "1"s

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1351] opened 2020-09-30 18:26 UTC
It is common in papers to number various headings, like:

![image](https://user-images.githubusercontent.com/31780210/94726192-e165ff80-032a-11eb-9fc6-59a6ba24a5e0.png)

But currently in the ISLE editor, as soon as you begin a line with a number followed by a period, it auto-formats it like an ordered list -- i.e., it auto-indents the number (even if I don't want to), and then the intervening text is confusing the ordered list functionality so that when you render it to pdf it thinks each subsequently numbered line is the beginning of a new ordered list and it converts all the numbers to "1":

![image](https://user-images.githubusercontent.com/31780210/94726225-edea5800-032a-11eb-9f66-aadb4d0f5561.png)

I think the best solution is to turn off the ordered-list auto-formatting, so that beginning a line with a number followed by a period does not get auto-formatted like an ordered list; if the user wants an ordered list, they can select it from the ordered list button.

**Comment by Planeshifter** [comment] 2020-09-30 19:01
Would like to solicit a bit more feedback on this. Notice that in case one has selected one of the Level 1 - 5 headings, typing a number followed by a period does *not* result in an ordered list being inserted. I am somewhat doubtful that one would regularly want to insert headings that are not differently formatted from regular paragraphs at all.

Aside: Realized that when selecting one of Heading 3-5, the dropdown menu would not close automatically. That will be fixed with next release.

**Comment by gweinberg** [comment] 2020-09-30 19:08
Sorry I'm not understanding your comment.
The bug is that users/students very often want to have self-created phrases (e.g., announcing various parts of a paper, or announcing each new hypothesis), most naturally numbered.  In such cases, the user is not intending to make an ordered list.  But something internally is (I think?) taking it to be an ordered list, because the number auto-indents, and then subsequent numbers are convereted to all "1"s in the pdf.

**Comment by gweinberg** [comment] 2020-09-30 22:06
I realized after submitting that you might have been confused since I did not explain that the "1.", "2." had been typed *by hand* (not entered using an ordered list tool).  That's the most common use case, I suspect (at least in 36-200 it is), students wanting to just type, by hand, a numbered heading, and **not** wanting it to be an ordered list.

**Comment by Planeshifter** [comment] 2020-10-02 19:06
Fair, I was somehow just focused on whether typing a number followed by a period and having it turn into an ordered list is really something we should change. It's common for WYSIWYG editors to do this (e.g. Slack). R Markdown do the same or this editor right here on GitHub where I am typing my response. In fact, it's *the* way to write an ordered list in Markdown, so we would deviate from the standard which is not a good idea. My argument was that if one desires to insert a heading starting with say `1.`, then first selecting the heading level and then typing `1.` will prevent the text from rendering as a list.

Definitely need to look into the bug when rendering a PDF file. It seems that's caused by a third-party library we are using that doesn't recognize lists starting at a specified number. Will keep you posted here on progress about this issue.

**Comment by gweinberg** [comment] 2020-10-02 19:19
Ah I see, doing it as a heading instead of ordinary text.

Well, one reason the error is common in 36-200 is because it's something I did in the sample project, which was made on a version of the report editor that didn't have this functionality, and the students are merely mimicking the sample project.  So perhaps, at least from a classroom standpoint, a short term solution is for me to update the sample projects and use a heading in those locations.

**Comment by Planeshifter** [comment] 2021-08-03 05:33
This issue is meanwhile resolved as ordered lists start at the respective number in the exported PDFs.

**Closed by Planeshifter** 2021-08-03 05:33 UTC
Labels: bug, interesting-idea
